# Pull official base image
# FROM node:13.12.0-alpine
FROM node:13.12.0-alpine as builder

# Set working directory
WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

# stage 2 - build the final image and copy the react build files
FROM nginx:1.17.8-alpine
COPY --from=builder /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]