version: "3"
services:
    webclient-customer:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 3001:3001
        expose:
            - '3001'
        stdin_open: true